version: 1.0.0.{build}

# clone directory
clone_folder: c:\projects\darkloader

configuration: Release
platform: Any CPU
build:
  project: DarkLoader.sln
  verbosity: detailed

# scripts to run after build
after_build:
	- cd c:\projects\darkloader
	- copy c:\projects\darkloader\DarkLoader\bin\Release\DarkLoader.exe c:\projects\darkloader\DarkLoader.exe
	
artifacts:
	- path: DarkLoader.exe
	  name: DarkLoader.exe