version: 1.0.1.{build}

# clone directory
clone_folder: c:\projects\darkloader

configuration: Release
platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  project: DarkLoader.sln
  verbosity: normal

# scripts to run after build
before_build:
  - nuget restore
after_build:
  - cd c:\projects\darkloader
  - copy c:\projects\darkloader\DarkLoader\bin\Release\DarkLoader.exe c:\projects\darkloader\DarkLoader.exe
artifacts:
  - path: DarkLoader.exe
    name: DarkLoader.exe
